# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
