# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171020_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Inventory')),
            ],
            options={
                'db_table': 'inventory_requirement',
            },
        ),
        migrations.RemoveField(
            model_name='orderquantity',
            name='stock',
        ),
        migrations.AddField(
            model_name='inventoryrequirement',
            name='order_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.OrderQuantity'),
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='inventory',
            field=models.ManyToManyField(through='dashboard.InventoryRequirement', to='dashboard.Inventory'),
        ),
    ]
