# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171020_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequirement',
            name='checkout_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
