# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inventoryrequirement_checkout_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderquantity',
            name='checkout_quantity',
        ),
    ]
