# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171025_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_officer',
            new_name='is_office',
        ),
    ]
