# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171023_1505'),
        ('dashboard', '0011_auto_20171025_1156'),
    ]

    operations = [
    ]
