# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_merge_20171026_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='client', max_length=10),
            preserve_default=False,
        ),
    ]
