# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationseen',
            name='has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
