# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20171026_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='received_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='available_weight',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='inventoryrequirement',
            name='checkout_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='inventoryrequirement',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_per_production',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
