# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_orderquantity_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderquantity',
            name='job_number',
        ),
        migrations.AddField(
            model_name='order',
            name='job_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
