# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20171116_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='job_number',
            new_name='job_card_number',
        ),
    ]
