# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20171116_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(default='Roll', max_length=25),
        ),
    ]
