# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(default='roll', max_length=5),
        ),
    ]
